### ISSUE TITLE
Word tokenizer needs improvement

### ISSUE THREAD

**Issue by vehk** [aufziehvogel/sprakit-website#27]
In the word "Rheinland-Pfalz", one can select three words (Rheinland, -, and Pfalz). Make it so that it is two words (better), or one (best, since it is a proper noun).

**Comment by aufziehvogel** [comment]
Special characters at the end or beginning of words should not be individual words, e.g:

(, ), comma, dot, [, ], ",

but special chars in between a word should be part of that word (e.g. hyphen).

At least for German, English, and probably most other Western languages.

**Comment by aufziehvogel** [comment]
Numbers also should not be words

**Comment by aufziehvogel** [comment]
Special chars should not be tokens anymore since commit c434510740a4fb95551092658017a31e0d7248cd , but have not done any integration test yet (only unit test).
